name: ams2019
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - xarray
  - matplotlib
  - cython
  - scipy
  - netcdf4
  - wradlib
  - cartopy
  - h5py
  - boto
  - boto3
  - docutils
  - cython
  - pip
  - nodejs
  - nbserverproxy
  - ipyleaflet
  - pip:
    - git+https://github.com/ARM-DOE/pyart.git
    - git+https://github.com/openradar/PyDDA.git
    - kubernetes
    - graphviz
    - nexradaws
    - cdsapi
    - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git